server.port=8000

spring.datasource.url=jdbc:mysql://localhost:3306/wellness_ca?useSSL=false&serverTimezone=Asia/Singapore
spring.datasource.username=root
spring.datasource.password=ly196812
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.open-in-view=false

app.jwt.secret=ThisIsAVeryLongJwtSecretKeyForLocalDevelopment123456
app.jwt.expiration=1440
app.gateway.token=team-wellness-2025
app.deepseek.key=test
app.rag.url=http://localhost:8001
